### PR TITLE
Update for 2017

### PR DESCRIPTION
**Pull request by garyb**
- Made it compile with PureScript 0.11.3
- Made some inconsequential style changes (no problem if you don't want them, I can put it back :wink:)
- Switched the build & test to use `pulp`
- Removed the generated docs in favour of a link to pursuit (currently dead, need to make this release first :smile:)
- Added some stuff to the README

### CODE REVIEW

**Comment by joneshf** [comment]
Amazing! Thanks so much!

I'd like to keep the metadata in `package.json`. I can add that back in a bit though so you don't have to (unless you're feeling extra generous). Otherwise, looks good to merge.

**Comment by garyb** [comment]
Oops, will do, I didn't mean to delete that, just forgot after copying in a `package.json` from elsewhere.

**Comment by joneshf** [comment]
I'm actually not going to be the one merging this. I added you as a collaborator. Feel free to merge whenever you feel ready.

**Comment by joneshf** [comment]
The same goes for anything you add in the future.

**Comment by garyb** [comment]
Ok, thanks!

**Pull request merged**
